<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Data</AssemblyName>
    <Deterministic>true</Deterministic>
    <OutputType>Library</OutputType>
    <RootNamespace>Bookstore.Data</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="*" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.8.2" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.7.7" />
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.1.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Bookstore.Domain/Bookstore.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
</Project>