<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RollForward>Major</RollForward>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Common\Bookstore.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.CDK.Lib" Version="2.238.0" />
    <PackageReference Include="Cdklabs.CdkNag" Version="2.37.55" />
    <PackageReference Include="Constructs" Version="10.4.5" />
    <PackageReference Include="Amazon.Jsii.Analyzers" Version="*" />
  </ItemGroup>
</Project>