<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Rekognition" Version="3.7.500" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.500" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.500" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
  </ItemGroup>
</Project>