<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Bookstore.Common/Bookstore.Common.csproj"></ProjectReference>
    <ProjectReference Include="../Bookstore.Data/Bookstore.Data.csproj"></ProjectReference>
    <ProjectReference Include="../Bookstore.Domain/Bookstore.Domain.csproj"></ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="[4.0.0, 5.0.0)" />
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.0" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.0" />
    <PackageReference Include="Autofac" Version="8.2.1" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="AWS.Logger.Core" Version="4.0.0" />
    <PackageReference Include="AWS.Logger.NLog" Version="4.0.0" />
    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="8.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="8.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.5.0" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="3.1.0" />
  </ItemGroup>
</Project>